import { type ClassValue, clsx } from "clsx";
import { Types } from "mongoose";
import { twMerge } from "tailwind-merge";
import { ID, TWithId } from "../types/types";
import { StateStore } from "@/store/createBoardSlice";
import { AUTH_MESSAGES } from "@/validation/messages/auth.messages";

// generated by shadcn
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

// created by chatgpt
export function isBase64Image(imageData: string) {
  const base64Regex = /^data:image\/(png|jpe?g|gif|webp);base64,/;
  return base64Regex.test(imageData);
}

// created by chatgpt
export function formatDateString(dateString: string) {
  const options: Intl.DateTimeFormatOptions = {
    year: "numeric",
    month: "short",
    day: "numeric",
  };

  const date = new Date(dateString);
  const formattedDate = date.toLocaleDateString(undefined, options);

  const time = date.toLocaleTimeString([], {
    hour: "numeric",
    minute: "2-digit",
  });

  return `${time} - ${formattedDate}`;
}

export function generateId(length: number = 8): string {
  const letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
  const chars =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

  let id = letters[Math.floor(Math.random() * letters.length)];

  for (let i = 1; i < length; i++) {
    id += chars[Math.floor(Math.random() * chars.length)];
  }

  return id;
}

export function getNewOrder(prev?: number, next?: number) {
  if (!prev && !next) return 100;

  if (!prev) return next! / 2;

  if (!next) return prev + 100;

  return (prev + next) / 2;
}

export function getTypeColor(type?: string) {
  switch (type) {
    case "bug":
      return "error";
    case "done":
      return "primary";
    case "block":
      return "bakground.default";
    default:
      return "secondary";
  }
}

//**********  bord utils
export function normalizeArrayToObj<T extends TWithId>(
  data: T[],
  acc?: Record<string, T>,
) {
  if (typeof acc === "object") {
    return data.reduce((acc, cur) => {
      acc[String(cur._id)] = cur;
      return acc;
    }, acc);
  }
  return {};
}

type TRollbackHandler<T extends object> = {
  state: T;
  tempId: string;
  set: any;
  key: keyof StateStore;
};

export function RollbackHandler<T extends object>({
  key,
  set,
  state,
  tempId,
}: TRollbackHandler<T>) {
  const stateSnapshot = Object.values(state);
  const filterState = stateSnapshot.filter(
    (item) => String(item._id) !== tempId,
  );
  const finalData = normalizeArrayToObj(filterState, {});
  set({ [key]: finalData });
}
export function setRealDataToStateHelper<
  T extends object,
  P extends { _id: ID },
>(state: T, payload: P, tempId: string, set: any, key: keyof StateStore) {
  const stateSnapshot = Object.values(state);
  const updatedState = stateSnapshot.map((item) =>
    String(item._id) === tempId ? { ...item, _id: payload._id } : item,
  );
  const finalState = normalizeArrayToObj(updatedState, {});

  return finalState;
}

// Http helpers

export function SafeParser<T>(data: any): T {
  return JSON.parse(JSON.stringify(data));
}
